let clientEventDefine = {
    //custom event define
    CUSTOM_EVENT_PLAYER_DATA_GET: 'CUSTOM_EVENT_PLAYER_DATA_GET',
    CUSTOM_EVENT_CLUB_DATA_REQ_FINISHED: 'CUSTOM_EVENT_CLUB_DATA_REQ_FINISHED',
    CUSTOM_EVENT_CLUB_MEMBER_REQ_FINISHED: 'CUSTOM_EVENT_CLUB_MEMBER_REQ_FINISHED',
    CUSTOM_EVENT_CLUB_MEMBER_GET: 'CUSTOM_EVENT_CLUB_MEMBER_GET',
    CUSTOM_EVENT_PLAYER_DATA_REQ_FINISHED: 'CUSTOM_EVENT_PLAYER_DATA_REQ_FINISHED',
    CUSTOM_EVENT_NEW_RECORD_ADDED: 'CUSTOM_EVENT_NEW_RECORD_ADDED',
    CUSTOM_EVENT_NEW_WIN_TYPE_ADDED: 'CUSTOM_EVENT_NEW_WIN_TYPE_ADDED'
};

export default clientEventDefine;